### ISSUE TITLE
要不要考虑用结构化日志来取代事件系统

### ISSUE THREAD

**Issue by VergilGao** [D-Walter/silancer#5]
现在这个引发事件的方式，订阅方的异常传播过来直接主线程就崩了。
可以考虑用结构化日志，Serilog就很好：
比如当成功发射一条弹幕，写日志：
{"id":12312,"code":"success"}
这样如果有第三方调用（比如UI）完全可以通过解析日志来接入。

还有一种思路是单独实现一个消息总线，主线程把消息塞到消息总线里就继续跑了。

**Comment by D-Walter** [comment]
我这里只是测试用的主线程，后面会重新封装命令行
只是这两天我受了点外伤比较麻烦，所以进展贼慢
